---
- name: download hugo
  get_url:
    url: "{{hugo_release}}"
    dest: /tmp/hugo.tar.gz

- name: extract hugo
  become: true
  unarchive:
    src: /tmp/hugo.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [hugo]

- name: clone my hugo repo
  git:
    repo: https://github.com/rexroof/rex-hugo
    dest: /tmp/rex-hugo

- name: build hugo site
  command: hugo
  args:
    chdir: /tmp/rex-hugo

- name: sync up hugo site with html
  become: true
  command: rsync --delete -av /tmp/rex-hugo/public/ /usr/share/nginx/html/
