---
- name: download hugo
  get_url:
    url: "{{hugo_release}}"
    dest: /tmp/hugo.tar.gz

- name: extract hugo
  become: true
  unarchive:
    src: /tmp/hugo.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [hugo]

- name: clone my hugo repo
  git:
    repo: git@github.com:rexroof/rex-hugo.git
    dest: rex-hugo
