---
- name: install packages
  yum:
    name: "{{item}}"
  become: true
  with_items:
    - nginx
    - git
    - tmux

- name: start up nginx
  become: true
  service:
    name: nginx
    state: started
    enabled: true
