---
- name: create aws linux instance
  hosts: 127.0.0.1
  vars:
    host_stub: "demo_box"
    a_date: "{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}"
    a_time: "{{ansible_date_time.hour}}{{ansible_date_time.minute}}"
    ec2_hostname: "{{host_stub}}_{{a_date}}{{a_time}}"

  tasks:
    - name: launch instance
      ec2:
        key_name: jenkins-demo
        region: "us-east-1"
        instance_type: t2.micro
        image: ami-a4c7edb2
        wait: yes
        vpc_subnet_id: subnet-5d92da77
        group_id: sg-ad9089dc
        assign_public_ip: yes
        instance_tags:
          Name: "{{ec2_hostname}}"
          Purpose: "Demo"
        exact_count: 1
        count_tag:
          Purpose: "Demo"
      register: ec2_hosts

    - name: create temporary facts
      set_fact:
        new_ami_private: "{{ item.private_ip }}"
        new_ami_public:  "{{ item.public_ip }}"
        new_instance_id: "{{ item.id }}"
      with_items: "{{ec2_hosts.instances|union(ec2_hosts.tagged_instances)}}"

    - name: add host to inventory
      add_host:
        hostname: "jenkins-demo"
        groups: "demo"
        ansible_host: "{{new_ami_public}}"
        ansible_user: "ec2-user"
        aws_instance: "{{new_instance_id}}"

    - name: set root volume to delete on termination
      local_action: >
        shell aws ec2 modify-instance-attribute
        --instance-id {{new_instance_id}}
        --block-device-mappings 
        '[{"DeviceName": "/dev/sda1",
        "Ebs":{"DeleteOnTermination":true}}]'
      when: false # not needed

    - name: register this with dns on route53
      route53:
        state: present
        zone: demo.neomyte.net
        record: demo.neomyte.net
        type: A
        ttl: 600
        value: "{{new_ami_public}}"

    - name: wait for ssh to come up on instance
      local_action:
        module: wait_for
        port: 22
        host: "{{new_ami_public}}"
        delay: 5
        search_regex: "OpenSSH"
        timeout: 500
